<a href="https://colab.research.google.com/github/jdre1/Machine-Learning-Bootcamp/blob/main/supervised/01_basic/linear_regression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import bibliotek do cwiczenie gradient descent

In [24]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

### Generowanie danych

In [25]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [26]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [27]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [28]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [29]:
eta = 0.01
weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.49671415]
 [-0.1382643 ]]


In [30]:
intercept = []
coef = []

for i in range(5000):
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
    weights = weights - eta * gradient
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

print(weights)

[[2749.99997064]
 [ 250.00000686]]


In [31]:
df = pd.DataFrame(data={'intercept': intercept, 'coef': coef})
df.head()

intercept        coef
0   72.996458  268.202239
1  125.262372  450.071141
2  163.752145  573.114529
3  192.859085  656.140472
4  215.572070  711.944393

In [32]:
px.line(df, y='intercept', width=800, title='Dopasowanie: intercept')

In [33]:
px.line(df, y='coef', width=800, title='Dopasowanie: coef')

##### Concatenation of two arrays Data (two-dimensional) and Target (one- dimensional)